### ISSUE TITLE
Profile / save selections

### ISSUE THREAD

**Issue by mikkel-ol** [TheSorm/RetSim#1]
Firstly, thank you for a great sim.

I am missing the option to save a profile in the WPF app.

It is cumbersome to set everything up again after closing the app.

A possibility would be to auto-save on selection.

**Comment by tasosgretsistas** [comment]
Hey, thank you for your kind words :)

This is currently among our highest priorities. It is not 100% necessary to get the sim running so we haven't gotten round to it yet, but it fairly simple to implement so expect to see it added soon (TM).

-Pride/Baranor
