### ISSUE TITLE
Heroic Presence is not automatically active when you select Draenei as your race

### ISSUE THREAD

**Issue by ghost** [TheSorm/RetSim#11]
![grafik](https://user-images.githubusercontent.com/64104540/155502915-db31ae87-090f-44a7-bbb7-26c9fe65904d.png)

With improved Faerie Fire, this would leave a 0.21% chance to miss, which should be completely eliminated by the additional 1% granted by heroic presence. As you can see, there are still some misses happening.

When selecting Heroic Presence in the buff section, these misses do not occur. However, since Draenei Paladins can't NOT have this extra 1% hit, it should be active without ticking the box. I also feel like it should be displayed in the stat summary, because for Draenei it is very much a racial feature rather than a buff (it isn't displayed as a buff ingame, either).

This is the string for the setup used when I noticed this issue, although you might need several tries and check the "min" result because the chance for a miss is still very low:

A0YAgUB965QDAH6ZIH3ZAgB1RoMgdWeKWQB9wY8ggWKE1AB904VgeQ5tOAB9wSB9wUB9wYkAfz5s-4oAdPuEywZAdZoAfcEgfdOHIHkRiqIAgWuIQH5ubS8AgWsgfdmLAH5PbReMAHhybRcNAHCeDgByxxIAa1yQAH5MbVA

This setup that just barely reaches 5% hit gets misses more consistently:

A0YAgUB-eJQDAH3BIH6ZAgB1RoMgdWeKWQB9wY8ggWKE1AB904UAfm1tOIkAfz5s-4oAdPuEywZAdZoAfcEgfdOHIHkRiqIAgWuIQH5ubS8AgWsgfdmLAH5PbReMAHhybRcNAHCeDgByxxIAa1yQAH5MbVA

**Comment by tasosgretsistas** [comment]
Hey, we're aware of this -- however, we'd like to give people a chance to sim with their racial inactive if they so desire, so we did not enforce Heroic Presence as always on if your race is Draenei, you have to select it yourself. It's a bit unintuitive I agree, but in general we prefer giving people options.
