### ISSUE TITLE
Can't Find Phase 4 items

### ISSUE THREAD

**Issue by templar100** [TheSorm/RetSim#14]
Can't find the phase 4 items such as Cloak of Fiends or Brooch of Deftness in the SIM. Not sure if there has been an update or not for this. Thanks

**Comment by templar100** [comment]
also, Skullshatter Warboots, Signet of Primal Wrath, Shallow-Grave Trousers, Master Assassin Wristwraps, Jinrokh... may be a few more but these I would like to SIM. Thanks!

**Comment by TheSorm** [comment]
Enable Phase 4 in the settings and you will see all of those items.
