### ISSUE TITLE
CTD when choosing gem for yellow gem socket

### ISSUE THREAD

**Issue by Equeslucis** [TheSorm/RetSim#2]
When using the compiled desktop version of the 28. November, i get a crash to desktop(CTD) shortly after choosing a gem for the yellow socket in the Settings tab.

As a workaround i tried to put the gems in the config file. I had success, the additional stats are shown in the left stat window. Unfortunately, simming gear apart from weapons does not work anymore. If i press the button all sim buttons are greyed out but nothing else happens (also no CPU usage). Personal DPS Sim with chosen gear works.

Also, after manually editing the config file, i no longer experience CTDs

![grafik](https://user-images.githubusercontent.com/93723035/144343308-bddb4a63-1961-4a5d-a3c1-8dd9a5546a46.png)

**Comment by TheSorm** [comment]
Hey, thanks for your feedback! :)

Can you please try to reproduce the issue with the newest version and give us feedback after? 
Also if you still have the problem to chose the gems in the settings, could you maybe show your settings.json so we can reproduce that issue :)

-Sules

**Comment by Equeslucis** [comment]
Hey, thanks for replying so fast!

i did reproduce the issue withthe newest version with the following steps:

compile new version
settings was not overwritten, so i deleted the gem IDs in settings.json
start sim
choose my gear
choose gems for sockets (8 str, 4 str 4 crit, 4 str 6 sta, relentless)
unmark divine wisdom in talents
choose 2/3 sanctified jugdement

crash

that crash only happens if i do choose gems before

Thanks for looking into that issue!
-Equeslucis

**Comment by TheSorm** [comment]
I can sadly not reproduce this.

Can you either post how your settings.json looks like before you start the sim and/or post the stacktrace / error massage?

-Sules

**Comment by Equeslucis** [comment]
[settings.zip](https://github.com/TheSorm/RetSim/files/7641595/settings.zip)

i do not know where to find the stracktrace/error message

**Comment by TheSorm** [comment]
Is it only happening with the specific gear you select?
So if you dont select your gear and ceep it at default, dose this also happens?

If it dose not happen, it would be great if you could post the gear you are selecting :)

**Comment by Equeslucis** [comment]
Nope, also happens with other gear. 
Also, this time it already crashed when choosing a red gem

**Comment by tasosgretsistas** [comment]
> Nope, also happens with other gear. Also, this time it already crashed when choosing a red gem

Can you please try to reproduce this issue in the release version?
https://github.com/TheSorm/RetSim/releases/tag/release

**Comment by Equeslucis** [comment]
Bug does not occur anymore in the release version
