### ISSUE TITLE
Missing Item "Vindicator's Band of Triumph" in P3 Gearset

### ISSUE THREAD

**Issue by Equeslucis** [TheSorm/RetSim#8]
Hey,

i wanted to sim my PvP gear to determine some stat weights and noticed that the new S3 PvP ring is missing in the P3 Gearset, it only enables with P4.
https://tbc.wowhead.com/item=33919/vindicators-band-of-triumph

**Comment by tasosgretsistas** [comment]
I fixed this in a new commit. We pulled item data from Wowhead, which unfortunately had a lot of the Phase information wrong as they were simply guessing which phase items come with. Let us know if you notice any other similar issues
