### ISSUE TITLE
Release for L/Unix

### ISSUE THREAD

**Issue by xpdable** [TheSorm/RetSim#9]
Hey bro, Ret player & Programmer. Any plan to make a release on MacOS? Anything I could help, though I do not know C#.... I work on macos.

--------------------------------
Operating Systems
As our project uses WPF, it is limited to Windows only for now. However, we may consider Linux / macOS releases at a later point. If you're a Linux or macOS user who wants to help us test releases for those systems, contact us.

**Comment by dukenukemx** [comment]
I second this but also for Linux.  As of right now due to the requirement of Webview2, this cannot be run on Wine.  I believe Webview2 requires dotnet 4.7.2 but Winetricks cannot install beyond dotnet 4.6.2.  So I gotta run Windows in a virtual machine in order to run RetSim.

**Comment by tasosgretsistas** [comment]
> I second this but also for Linux. As of right now due to the requirement of Webview2, this cannot be run on Wine. I believe Webview2 requires dotnet 4.7.2 but Winetricks cannot install beyond dotnet 4.6.2. So I gotta run Windows in a virtual machine in order to run RetSim.

Yeah this is the type of information we'd like to know, so we know exactly what we would need to port over, besides WPF. If I'm being real, I cannot see a Linux / MacOS version coming soon as we're both currently very busy and it'd take a major re-write, but at the very least it's good to know what exactly needs to be re-written.

**Comment by xpdable** [comment]
no worries. afk -ed. no more wow.
